name = "leansort"
version = "0.1.0"
defaultTargets = ["LeanSort"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "e06eff5f95374108acfaf19f1ff7473aa7771df2"

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib.git"
rev = "d9be64196bf145edd019f1ccfeaee0c11166ba6b"

[[lean_lib]]
name = "LeanSort"
